Map<String, String> en() {
  return {
    'payodaPremiereLeague': 'Payoda Premiere\nLeague',
    'proceedWithYour': 'Proceed with your',
    'login': 'Login',
    'emailUsername': 'Email/Username*',
    'emailAddress': 'Email address*',
    'password': 'Password*',
    'forgotPassword?': 'Forgot Password?',
    'signIn': 'Sign In',
    'orSignInWith': 'Or sign in with',
    'gmail': 'Gmail',
    'forgotPassword': 'Forgot Password',
    'verification': 'Verification',
    'sendVerificationCode': 'Send Verification Code',
    'enterCode': 'Enter Code',
    'verify': 'Verify',
    'didReceivedCode': 'Didn’t received code? ',
    'enterNewPassword': 'Enter new password*',
    'confirmNewPassword': 'Confirm new password*',
    'createPassword': 'Create Password',
    'createNewPassword': 'Create New Password',
    'success': 'Success!',
    'goToLogin': 'Go to Login',
    'redirectingIn': 'Redirecting in ',
    'sec': ' sec',
    'teams': ' Teams',
    'leaderboard': ' Leaderboard',
    'engagements': ' Engagements',
    'connects': ' Connects',
    'createTeam': ' Create Team',
    'createEngagement': ' Create Engagement',
    'uploadTeams': 'Upload teams',
    'or': 'OR',
    'uploadLogo': 'Upload\nLogo',
    'uploadTeamLogo': 'Upload team logo*',
    'logoSizeShould': 'Logo size should be below ',
    'pngAndJpgAreAllowed': ' and only PNG or JPG are allowed.',
    'teamName': 'Team name*',
    'captain': 'Captain*',
    'viceCaptain': 'Vice captain*',
    'sponsor': 'Sponsor*',
    'upload': 'Upload',
    'uploadTeamMembers': 'Upload team members',
    'searchByEmployeeName': 'Search by employee name',
    'chooseTeamCaptain': 'Choose Team Captain',
    'chooseTeamViceCaptain': 'Choose Team Vice Captain',
    'chooseTeamSponsor': 'Choose Team Sponsor',
    'done': 'Done',
    'addTeam': 'Add Team',
    'teamAvgWinningRate': 'Team avg winning rate - ',
    'points': 'Points',
    'winner': 'Winner',
    'allEmployees': 'All Employees',
    'participants': 'Participants',
    'uploadTeam': 'Upload Team(s)',
    'dragOrDropCsvHere': 'Drag or Drop CSV here',
    'upload_engagement_details': 'Upload engagement details',
    'browseFile': 'Browse file',
    'downloadSampleCsvHere': 'Download sample CSV here',
    'selectAll': 'Select All',
    'assignToTeam': 'Assign to team',
    'teamParticipatingUpcomingEvents': 'Team Participating - Upcoming Events',
    'youHaveNoTeam': "You haven't created or joined any teams yet. Teams are the heart in PPL. Start by creating a team or joining an existing one to get things done together.",
    'successDesc': 'You have successfully created a password. Please give us a seconds to redirect to login page or click below button to go to login page.',
    'createPasswordDesc': 'Account validation is success! Please create new password and proceed with login.',
    'enterTheVerificationCodeWeJustSentToYourEmailAddress':
        'Enter the verification code we just sent to your email address.',
    'pleaseEnterYourEmailAddressToReceiveAVerificationCode':
        'Please enter your email address to receive a\nverification code.',
    'engagement_type': 'Engagement type*',
    'event_name': 'Event name*',
    'ppl_points': 'PPL points*',
    'create_event': 'Create Event'
  };
}
